// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pammfsgnafvsxswiuoyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbW1mc2duYWZ2c3hzd2l1b3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDM2MzAsImV4cCI6MjA2MzYxOTYzMH0.hCtyrtnKjUllhj1RN_-VFIUIwOJiunL6iR9jabrpjAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);